//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 NcInterface.rc 使用
//
#define IDR_MANIFEST                    1
#define IDS_STRING2                     2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MESSAGEBOXEX                108
#define IDD_UNINSTALL1                  109
#define IDD_IMPORTREG                   110
#define IDD_PIC                         111
#define IDB_PIC_7_H                     138
#define IDB_PIC_7_N                     139
#define IDB_PIC_7_P                     140
#define IDB_PIC_8_H                     141
#define IDB_PIC_8_N                     142
#define IDB_PIC_8_P                     143
#define IDB_PIC_9_H                     144
#define IDB_PIC_9_N                     145
#define IDB_PIC_9_P                     146
#define IDR_MAINFRAME                   162
#define IDB_BITMAP1                     163
#define IDB_CLOSE_DOWN                  164
#define IDB_CLOSE_MASK                  165
#define IDB_CLOSE_NOR                   166
#define IDB_CLOSE_ON                    167
#define IDB_CHECK_NOR                   168
#define IDB_CHECK_OVER                  169
#define IDB_CHECK_DOWN                  170
#define IDB_CHECK_MASK                  171
#define IDB_CHECK_OVER2                 173
#define IDI_ICON1                       186
#define IDB_PNG1                        190
#define IDB_PNG_LOGO                    191
#define IDB_BIG_BG                      196
#define IDB_BIG_BG2                     201
#define IDB_BIG_BG3                     202
#define IDB_BIG_BG1                     204
#define IDB_BITMAP2                     205
#define IDB_BMP_SM_BG                   206
#define IDI_ICON2                       207
#define IDI_ICON3                       209
#define IDB_BIG_BG4                     211
#define IDB_BITMAP3                     212
#define IDB_CLOSE_EX_NOR                213
#define IDB_CLOSE_EX_ON                 214
#define IDB_SKYPE_BG1                   215
#define IDB_SKYPE_BG2                   216
#define IDB_SKYPE_BG3                   217
#define IDB_SKYPE_CLOSE1_NOR            218
#define IDB_SKYPE_CLOSE2_NOR            219
#define IDB_SKYPE_CLOSE3_NOR            220
#define IDB_SKYPE_CLOSE1_ON             221
#define IDB_SKYPE_CLOSE2_ON             222
#define IDB_SKYPE_CLOSE3_ON             223
#define IDB_BITMAP4                     226
#define IDB_PNG5                        229
#define IDB_RESULT_2                    229
#define IDB_PNG15                       287
#define IDB_KEYBOARDLED_AUTO            287
#define IDB_KEYBOARDLED_MIN             288
#define IDB_KEYBOARDLED_MAX             289
#define IDB_KEYBOARDLED_CLOSE           290
#define IDB_CAMERA_LOCK                 291
#define IDB_CAMERA_UNLOCK               292
#define IDB_CAPS_LOCK                   293
#define IDB_CAPS_UNLOCK                 294
#define IDB_FN_LOCK                     295
#define IDB_FN_UNLOCK                   296
#define IDB_ITS4_FA_TACHOMETER          297
#define IDB_ITS4_LE_BATTERY             298
#define IDB_ITS4_LE_INTERLLIGENTCOOL    299
#define IDB_MIC_MUTE                    300
#define IDB_MIC_UNMUTE                  301
#define IDB_NUMBER_LOCK                 302
#define IDB_NUMBER_UNLOCK               303
#define IDB_TP_LOCK                     304
#define IDB_TP_UNLOCK                   305
#define IDB_CLODE_1                     306
#define IDB_CLOSE_1                     306
#define IDB_CLOSE_2                     307
#define IDB_RESULT_1                    308
#define IDB_RESULT_3                    312
#define IDB_CHECK                       315
#define IDB_DEFAULT                     316
#define IDB_TIME_1S                     317
#define IDB_TIME_2S                     318
#define IDB_TIME_3S                     319
#define IDB_TIME_4S                     320
#define IDB_TIME_5S                     321
#define IDB_TIME_ALWAYS                 322
#define IDB_TIME_1S_1                   324
#define IDB_TIME_2S_1                   325
#define IDB_TIME_3S_1                   326
#define IDB_TIME_4S_1                   327
#define IDB_TIME_5S_1                   328
#define IDB_TIME_ALWAYS_1               329
#define IDC_BUTTON1                     1000
#define IDC_QUIT                        1001
#define IDC_BUTTON2                     1002
#define IDC_APP_ICON_1                  1003
#define IDC_APP_ICON_2                  1004
#define IDC_APP_ICON_3                  1005
#define IDC_APP_ICON_6                  1006
#define IDC_APP_ICON_4                  1007
#define IDC_APP_ICON_5                  1008
#define IDC_APP_ICON_7                  1009
#define IDC_APP_ICON_8                  1010
#define IDC_APP_ICON_9                  1011
#define IDC_PROGRESS1                   1012
#define IDC_APP_ICON_1_1                1012
#define IDC_APP_ICON_2_1                1013
#define IDC_APP_ICON_3_1                1014
#define IDC_APP_ICON_4_1                1015
#define IDC_APP_ICON_5_1                1016
#define IDC_APP_ICON_6_1                1017
#define IDC_APP_ICON_7_1                1018
#define IDC_APP_ICON_7_2                1019
#define IDC_APP_ICON_8_1                1020
#define IDC_APP_ICON_8_2                1021
#define IDC_APP_ICON_8_3                1022
#define IDC_BTN_TIME                    1023
#define IDC_BTN_CHECK                   1024
#define IDC_BTN_TIME5                   1024
#define IDC_BTN_RESULT                  1025
#define IDC_BTN_FRAME                   1025
#define IDC_BTN_DEFAULT                 1026
#define IDC_BTN_TIMEALWAYS              1026
#define IDC_BTN_TIME2                   1027
#define IDC_BTN_TIME3                   1028
#define IDC_BTN_TIME4                   1029
#define IDC_BTN_RESULT2                 1030
#define IDC_BTN_TIME_1                  1030
#define IDC_BTN_RESULT3                 1031
#define IDC_BTN_TIME2_1                 1031
#define IDC_BTN_TIME3_1                 1032
#define IDC_BTN_TIME4_1                 1033
#define IDC_BTN_TIME5_1                 1034
#define IDC_BTN_TIMEALWAYS_1            1035
#define IDS_HELPFILE                    2001
#define IDS_GOHOME_DLG                  2002
#define IDS_GOHOME_DLG_FILDFILE_BTN     2003
#define IDS_GOHOME_DLG_CLEARFILE_BTN    2004
#define IDS_GOHOME_DLG_CHECK_BTN        2005
#define IDS_GOHOMECLEARFILE_BTNDLG      2006
#define IDS_GOHOMECLEARFILE_MSGDLG      2006
#define IDS_GOHOMEPATHNOTEXIST_MSGDLG   2007
#define IDS_GOHOMEERROR_DLG             2008
#define IDS_GOHOMEERROR_DLG_QUIT_BTN    2009
#define IDS_OBE_DLG                     2010
#define IDS_GOHOMEFAILED_DLG            2011
#define IDS_GOHOMEFAILED_DLG_REPAIR_BTN 2012
#define IDS_GOHOMEFAILED_DLG_QUIT_BTN   2013
#define IDS_IMPORTREG_DLG               2014
#define IDS_ISGOHOME_DLG                2015
#define IDS_ISGOHOME_DLG_CONTIUNE_BTN   2016
#define IDS_ISGOHOME_DLG_QUIT_BTN       2017
#define IDS_ISGOHOME_CONTIUNE_MSGDLG    2018
#define IDS_REPAIROK_MSGDLG             2019
#define IDS_REPAIRFAILED_MSGDLG         2020
#define IDS_UNINSTALL_DLG               2021
#define IDS_UNINSTALL_CONTIUNE_MSGDLG   2022
#define IDS_UNINSTALL_DLG_CONTIUNE_BTN  2023
#define IDS_UNINSTALL_DLG_QUIT_BTN      2024
#define IDS_MESSAGEBOXEX_OK             2025
#define IDS_MESSAGEBOXEX_CANCEL         2026
#define IDS_PROGRAM_FILE_NOT_EXIST      2027
#define IDS_REBOOTSYS_DLG               2028
#define IDS_REBOOTSYS_DLG_BTN           2029
#define IDS_STRING2030                  2030
#define IDS_REBOOTSYS_DLG_COUNT_TIME    2030
#define IDS_OBE_DLG_ENABLE_BTN          2031
#define IDS_OBE_DLG_ENABLE_BTN2         2031
#define IDS_OBE_DLG_DISABLE_BTN         2032
#define IDS_OBE_DLG_DISABLE_BTN2        2032
#define IDS_ADDMENU_GOHOME_TIP          2033
#define IDS_ADDMENU_GOHOME_TIP2         2033
#define IDS_STOPCREATERECOVER_MSGDLG    2034
#define IDS_STOPCREATERECOVER_MSGDLG2   2034
#define IDS_MENU_HELP                   2035
#define IDS_MENU_UNINSTALL              2036
#define IDS_MENU_FINDFILE               2037
#define IDS_MENU_INITINSTANT            2038
#define IDS_IS_UNINSTALL                2039
#define IDS_UNINSATLL_END               2040
#define IDS_INSTALL_SUCCESS             2041
#define IDS_OBE_DLG_PAGE1               2042
#define IDS_OBE_DLG_PAGE2               2043
#define IDS_START_NC_NO_FREE_SPACE      2044
#define IDS_STRING2045                  2045
#define IDS_START_NC_NO_RIGHTS          2045
#define IDS_START_NC_NO_RIGHTS2         2046

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        330
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1026
#define _APS_NEXT_SYMED_VALUE           147
#endif
#endif
